// Generated by gencpp from file lidar_msgs/Curb.msg
// DO NOT EDIT!


#ifndef LIDAR_MSGS_MESSAGE_CURB_H
#define LIDAR_MSGS_MESSAGE_CURB_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lidar_msgs/PointStamped.h>

namespace lidar_msgs
{
template <class ContainerAllocator>
struct Curb_
{
  typedef Curb_<ContainerAllocator> Type;

  Curb_()
    : header()
    , points()  {
    }
  Curb_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , points()  {
  (void)_alloc;
      points.assign( ::lidar_msgs::PointStamped_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::lidar_msgs::PointStamped_<ContainerAllocator> , 100>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::lidar_msgs::Curb_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_msgs::Curb_<ContainerAllocator> const> ConstPtr;

}; // struct Curb_

typedef ::lidar_msgs::Curb_<std::allocator<void> > Curb;

typedef boost::shared_ptr< ::lidar_msgs::Curb > CurbPtr;
typedef boost::shared_ptr< ::lidar_msgs::Curb const> CurbConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_msgs::Curb_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_msgs::Curb_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_msgs::Curb_<ContainerAllocator1> & lhs, const ::lidar_msgs::Curb_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_msgs::Curb_<ContainerAllocator1> & lhs, const ::lidar_msgs::Curb_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::Curb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_msgs::Curb_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::Curb_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_msgs::Curb_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::Curb_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_msgs::Curb_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_msgs::Curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75af1c1affc9fe6f9de6b476e4c14f22";
  }

  static const char* value(const ::lidar_msgs::Curb_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75af1c1affc9fe6fULL;
  static const uint64_t static_value2 = 0x9de6b476e4c14f22ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_msgs::Curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_msgs/Curb";
  }

  static const char* value(const ::lidar_msgs::Curb_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_msgs::Curb_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"PointStamped[100] points\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: lidar_msgs/PointStamped\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 intensity\n"
;
  }

  static const char* value(const ::lidar_msgs::Curb_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_msgs::Curb_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Curb_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_msgs::Curb_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_msgs::Curb_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_MSGS_MESSAGE_CURB_H
