# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_msgs/BoxInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lidar_msgs.msg

class BoxInfo(genpy.Message):
  _md5sum = "7f621b8f09e614f07fb08a2b7f9a6583"
  _type = "lidar_msgs/BoxInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """box box

================================================================================
MSG: lidar_msgs/box
float32 x_min
float32 y_min
float32 z_min
float32 x_max
float32 y_max
float32 z_max
"""
  __slots__ = ['box']
  _slot_types = ['lidar_msgs/box']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       box

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoxInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.box is None:
        self.box = lidar_msgs.msg.box()
    else:
      self.box = lidar_msgs.msg.box()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.box.x_min, _x.box.y_min, _x.box.z_min, _x.box.x_max, _x.box.y_max, _x.box.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = lidar_msgs.msg.box()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.box.x_min, _x.box.y_min, _x.box.z_min, _x.box.x_max, _x.box.y_max, _x.box.z_max,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.box.x_min, _x.box.y_min, _x.box.z_min, _x.box.x_max, _x.box.y_max, _x.box.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box is None:
        self.box = lidar_msgs.msg.box()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.box.x_min, _x.box.y_min, _x.box.z_min, _x.box.x_max, _x.box.y_max, _x.box.z_max,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
