# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from lidar_msgs/SocketBox.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import lidar_msgs.msg

class SocketBox(genpy.Message):
  _md5sum = "7e7c1fed7bbc79bff735bfacc0aaebc3"
  _type = "lidar_msgs/SocketBox"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 num_of_box
BoxInfo[] box_info

================================================================================
MSG: lidar_msgs/BoxInfo
box box

================================================================================
MSG: lidar_msgs/box
float32 x_min
float32 y_min
float32 z_min
float32 x_max
float32 y_max
float32 z_max
"""
  __slots__ = ['num_of_box','box_info']
  _slot_types = ['int32','lidar_msgs/BoxInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       num_of_box,box_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SocketBox, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.num_of_box is None:
        self.num_of_box = 0
      if self.box_info is None:
        self.box_info = []
    else:
      self.num_of_box = 0
      self.box_info = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.num_of_box
      buff.write(_get_struct_i().pack(_x))
      length = len(self.box_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.box_info:
        _v1 = val1.box
        _x = _v1
        buff.write(_get_struct_6f().pack(_x.x_min, _x.y_min, _x.z_min, _x.x_max, _x.y_max, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box_info is None:
        self.box_info = None
      end = 0
      start = end
      end += 4
      (self.num_of_box,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.box_info = []
      for i in range(0, length):
        val1 = lidar_msgs.msg.BoxInfo()
        _v2 = val1.box
        _x = _v2
        start = end
        end += 24
        (_x.x_min, _x.y_min, _x.z_min, _x.x_max, _x.y_max, _x.z_max,) = _get_struct_6f().unpack(str[start:end])
        self.box_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.num_of_box
      buff.write(_get_struct_i().pack(_x))
      length = len(self.box_info)
      buff.write(_struct_I.pack(length))
      for val1 in self.box_info:
        _v3 = val1.box
        _x = _v3
        buff.write(_get_struct_6f().pack(_x.x_min, _x.y_min, _x.z_min, _x.x_max, _x.y_max, _x.z_max))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.box_info is None:
        self.box_info = None
      end = 0
      start = end
      end += 4
      (self.num_of_box,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.box_info = []
      for i in range(0, length):
        val1 = lidar_msgs.msg.BoxInfo()
        _v4 = val1.box
        _x = _v4
        start = end
        end += 24
        (_x.x_min, _x.y_min, _x.z_min, _x.x_max, _x.y_max, _x.z_max,) = _get_struct_6f().unpack(str[start:end])
        self.box_info.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
